name: Ci

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install cargo
      run: sudo apt install cargo rustfmt

    - name: Format
      run: cargo fmt --all --check

    - name: Build
      run: cargo build --release

    - name: Test
      run: cargo test

    - name: Test examples
      run: |
        for example in examples/*.yaml; do
          echo "Testing $example"
          cargo run --release -q -- -t foot create "$example"
          if [ $? -ne 0 ]; then
            echo "Failed to create example from $example"
            exit 1
          fi
          cargo run --release -q -- -t foot clear
        done
